### ISSUE TITLE
Error callURL

### ISSUE THREAD

**Issue by Goalpwr** [uncdubdiver/smartthings-govee-led-lights#1]
Receiving the following error:
6:54:57 PM: error callURL() <<<<<<<<<<<<<<<< ERROR <<<<<<<<<<<<<<<<
6:54:57 PM: error groovyx.net.http.ResponseParseException: Bad Request
6:54:57 PM: error Error: e.statusCode 400
6:54:57 PM: error callURL() >>>>>>>>>>>>>>>> ERROR >>>>>>>>>>>>>>>>
6:54:57 PM: trace Executing 'callURL(devicecontrol-power, on)'...
6:54:57 PM: trace Executing 'on()'...
6:54:50 PM: error groovy.lang.MissingPropertyException: No such property: data for class: java.lang.String @line 254 (refresh)
6:54:50 PM: error callURL() <<<<<<<<<<<<<<<< ERROR <<<<<<<<<<<<<<<<
6:54:50 PM: error groovyx.net.http.HttpResponseException: Bad Request
6:54:50 PM: error Error: e.statusCode 400
6:54:50 PM: error callURL() >>>>>>>>>>>>>>>> ERROR >>>>>>>>>>>>>>>>
6:54:50 PM: trace Executing 'callURL(devicestate, )'...
6:54:50 PM: trace Executing 'refresh()'...
6:54:50 PM: trace Executing 'updated()'..

**Comment by uncdubdiver** [comment]
Just to make sure, did you run the index.html file locally to get your device id from Govee?  You'll need your Govee app API KEY for it.
