### ISSUE TITLE
SmartThings hub required?

### ISSUE THREAD

**Issue by mike-mo** [uncdubdiver/smartthings-govee-led-lights#2]
I assume this requires a SmartThings Hub to be set up? If so, we should list it in the prerequisites section of the readme.

**Comment by uncdubdiver** [comment]
@mike-mo , yes that is correct.  Since this is a smartthings code for their Device Type Handlers, a SmartThings hub is essentially required.

**Comment by mpl241** [comment]
@uncdubdiver, I don't have a SmartThing Hub, but I can control two Govee devices using the SmartThings App and the device handler crated by the code from this project.  Thanks for sharing your code and the instructions for using it.  I am using SmartThings automation, to turn-on my Govee TV LED lights when I turn-on my Samsung TV.
